[package]
name = "graph-deps"
version = "0.1.0"
authors = ["tckastanek <28022361+tckastanek@users.noreply.github.com>"]

[dependencies]
clap = "^2.3"
dot = "^0.1"
failure = "^0.1.1"
failure_derive = "^0.1.1"
petgraph = "^0.4"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"